server:
  port: 7001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssm-java1?useSSL=false
    username: root
    password: root0314
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
